# Generated by Django 2.1.dev20180314090007 on 2018-06-16 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres_zamieszkania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=255)),
                ('numerBudynku', models.CharField(max_length=5)),
                ('numerLokalu', models.CharField(blank=True, max_length=5)),
                ('kodPocztowy', models.CharField(max_length=6)),
                ('miejscowosc', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Adresy_zamieszkania',
            },
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Kandydaci',
                'ordering': ['-votes'],
            },
        ),
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kraje',
            },
        ),
        migrations.CreateModel(
            name='Kryterium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlugoscGlosowania', models.IntegerField()),
                ('iloscPoprartychKandydatow', models.IntegerField()),
                ('votes', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name_plural': 'Kryteria',
            },
        ),
        migrations.CreateModel(
            name='Oddany_glos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOddaniaGlosu', models.DateTimeField(verbose_name='data oddania glosu')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Oddane_głosy',
            },
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('pesel', models.CharField(max_length=11)),
                ('adresZamieszkania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Adres_zamieszkania')),
            ],
            options={
                'verbose_name_plural': 'Osoby',
            },
        ),
        migrations.CreateModel(
            name='Uprawniony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Osoba')),
            ],
            options={
                'verbose_name_plural': 'Uprawnieni',
            },
        ),
        migrations.CreateModel(
            name='Wybor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=255)),
                ('dataRozpoczecia', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataZakonczenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('opis', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('kryterium', models.ManyToManyField(to='polls.Kryterium')),
            ],
            options={
                'verbose_name_plural': 'Wybory',
            },
        ),
        migrations.AddField(
            model_name='uprawniony',
            name='wybor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Wybor'),
        ),
        migrations.AddField(
            model_name='oddany_glos',
            name='wybor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Wybor'),
        ),
        migrations.AddField(
            model_name='kandydat',
            name='osoba',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Osoba'),
        ),
        migrations.AddField(
            model_name='kandydat',
            name='wybor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Wybor'),
        ),
        migrations.AddField(
            model_name='adres_zamieszkania',
            name='kraj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Kraj'),
        ),
    ]
