# Generated by Django 2.1.dev20180314090007 on 2018-04-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('idKandydat', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('idKraj', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kryterium',
            fields=[
                ('idKryterium', models.AutoField(primary_key=True, serialize=False)),
                ('dlugoscGlosowania', models.IntegerField()),
                ('iloscPoprartychKandydatow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oddany_glos',
            fields=[
                ('idOddanyGlos', models.AutoField(primary_key=True, serialize=False)),
                ('dataOddaniaGlosu', models.DateTimeField(verbose_name='data oddania glosu')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('idOsoba', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('pesel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Uprawniony',
            fields=[
                ('idUprawniony', models.AutoField(primary_key=True, serialize=False)),
                ('idOsoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Wybor',
            fields=[
                ('idWybor', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('dataRozpoczecia', models.DateTimeField(verbose_name='data rozpoczecia')),
                ('dataZakonczenia', models.DateTimeField(verbose_name='data zakonczenia')),
                ('opis', models.CharField(max_length=255)),
                ('idKryterium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Kryterium')),
            ],
        ),
        migrations.RemoveField(
            model_name='adres_zamieszkania',
            name='id',
        ),
        migrations.AlterField(
            model_name='adres_zamieszkania',
            name='idAdresZamieszkania',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adres_zamieszkania',
            name='idKraj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Kraj'),
        ),
        migrations.AddField(
            model_name='uprawniony',
            name='idWybor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Wybor'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='idAdresZamieszkania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Adres_zamieszkania'),
        ),
        migrations.AddField(
            model_name='oddany_glos',
            name='idUprawniony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Uprawniony'),
        ),
        migrations.AddField(
            model_name='oddany_glos',
            name='idWybor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Wybor'),
        ),
        migrations.AddField(
            model_name='kandydat',
            name='idOsoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Osoba'),
        ),
        migrations.AddField(
            model_name='kandydat',
            name='idWybor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Wybor'),
        ),
    ]
