# Generated by Django 2.1.dev20180314090007 on 2018-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180407_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres_zamieszkania',
            name='numerLokalu',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
