# Generated by Django 2.1.dev20180314090007 on 2018-04-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_adres_zamieszkania_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kraj',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='adres_zamieszkania',
            old_name='idKraj',
            new_name='idCountry',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='idKraj',
            new_name='idCountry',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='nazwa',
            new_name='name',
        ),
    ]
