# Generated by Django 2.1.dev20180314090007 on 2018-06-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180415_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='wybor',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
