# Generated by Django 2.1.dev20180314090007 on 2018-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180613_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wybor',
            name='active',
        ),
        migrations.AddField(
            model_name='kryterium',
            name='votes',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='wybor',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wybor',
            name='nazwa',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wybor',
            name='opis',
            field=models.CharField(default='', max_length=255),
        ),
    ]
