# Generated by Django 2.1.dev20180314090007 on 2018-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180408_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres_zamieszkania',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
