# Generated by Django 2.1.dev20180314090007 on 2018-04-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180414_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adres_zamieszkania',
            old_name='Kraj',
            new_name='kraj',
        ),
        migrations.RenameField(
            model_name='kandydat',
            old_name='Osoba',
            new_name='osoba',
        ),
        migrations.RenameField(
            model_name='kandydat',
            old_name='Wybor',
            new_name='wybor',
        ),
        migrations.RenameField(
            model_name='oddany_glos',
            old_name='Uprawniony',
            new_name='uprawniony',
        ),
        migrations.RenameField(
            model_name='oddany_glos',
            old_name='Wybor',
            new_name='wybor',
        ),
        migrations.RenameField(
            model_name='osoba',
            old_name='AdresZamieszkania',
            new_name='adresZamieszkania',
        ),
        migrations.RenameField(
            model_name='uprawniony',
            old_name='Osoba',
            new_name='osoba',
        ),
        migrations.RenameField(
            model_name='uprawniony',
            old_name='Wybor',
            new_name='wybor',
        ),
        migrations.RenameField(
            model_name='wybor',
            old_name='Kryterium',
            new_name='kryterium',
        ),
        migrations.RemoveField(
            model_name='adres_zamieszkania',
            name='idAdresZamieszkania',
        ),
        migrations.RemoveField(
            model_name='kandydat',
            name='idKandydat',
        ),
        migrations.RemoveField(
            model_name='kraj',
            name='idKraj',
        ),
        migrations.RemoveField(
            model_name='kryterium',
            name='idKryterium',
        ),
        migrations.RemoveField(
            model_name='oddany_glos',
            name='idOddanyGlos',
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='idOsoba',
        ),
        migrations.RemoveField(
            model_name='uprawniony',
            name='idUprawniony',
        ),
        migrations.RemoveField(
            model_name='wybor',
            name='idWybor',
        ),
        migrations.AddField(
            model_name='adres_zamieszkania',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kandydat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kraj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kryterium',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oddany_glos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osoba',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uprawniony',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wybor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
