# Generated by Django 2.1.dev20180314090007 on 2018-06-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_oddany_glos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddany_glos',
            name='uprawniony',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Uprawniony'),
        ),
    ]
