# Generated by Django 2.1.dev20180314090007 on 2018-06-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180616_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kandydat',
            options={'ordering': ['-votes'], 'verbose_name_plural': 'Kandydaci'},
        ),
        migrations.RemoveField(
            model_name='oddany_glos',
            name='uprawniony',
        ),
    ]
