# Generated by Django 2.1.dev20180314090007 on 2018-06-16 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_auto_20180616_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oddany_glos',
            name='user',
        ),
        migrations.AddField(
            model_name='oddany_glos',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
