# Generated by Django 2.1.dev20180314090007 on 2018-06-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20180616_1840'),
        ('polls', '0015_auto_20180616_1906'),
    ]

    operations = [
    ]
